----Step 1: (create a new user)
--CREATE LOGIN AruHiker WITH PASSWORD='caca', CHECK_POLICY = OFF;
---- Step 2:(deny view to any database)
--USE master;
--GO
--DENY VIEW ANY DATABASE TO AruHiker; 
---- step 3 (then authorized the user for that specific database , you have to use the  master by doing use master as below)
--USE master;
--GO

--USE AruKami
--CREATE USER AruHiker FOR LOGIN AruHiker
--GO

---- Permisos del usuario hiker
--GRANT EXEC ON [PR_CreateHiker] TO AruHiker
--GRANT EXEC ON [PR_HikerLogin] TO AruHiker
--GRANT EXEC ON [PR_CreateHike] TO AruHiker
--GRANT EXEC ON [PR_CreatePoint] TO AruHiker
--GRANT EXEC ON [PR_GetUser] TO AruHiker
--GRANT SELECT ON [Nationalities] TO AruHiker
--GRANT SELECT ON [Hike_Difficulty] TO AruHiker
--GRANT SELECT ON [Hike_Quality] TO AruHiker
--GRANT SELECT ON [Hike_Price] TO AruHiker
--GRANT SELECT ON [Hike_Type] TO AruHiker

---- Permisos del usuario administrador
--GRANT EXEC ON [PR_CreateAdmin] TO AruAdmin
--GRANT EXEC ON [PR_CreateAdminICT] TO AruAdmin
--GRANT EXEC ON [PR_AdminLogin] TO AruAdmin
--GRANT SELECT ON [View_User] TO AruAdmin
--GRANT SELECT ON [View_Quality] TO AruAdmin
--GRANT SELECT ON [View_Price] TO AruAdmin
--GRANT SELECT ON [View_Difficulty] TO AruAdmin
--GRANT SELECT ON [View_HikeType] TO AruAdmin
--GRANT EXEC ON [PR_InactiveQuality] TO AruAdmin
--GRANT EXEC ON [PR_InactiveAdminICT] TO AruAdmin
--GRANT EXEC ON [PR_InactivePrice] TO AruAdmin
--GRANT EXEC ON [PR_InactiveDifficulty] TO AruAdmin
--GRANT EXEC ON [PR_InactiveHikeType] TO AruAdmin
--GRANT EXEC ON [PR_InactiveAdmin] TO AruAdmin
--GRANT EXEC ON [PR_ActiveQuality] TO AruAdmin
--GRANT EXEC ON [PR_ActiveAdminICT] TO AruAdmin
--GRANT EXEC ON [PR_ActivePrice] TO AruAdmin
--GRANT EXEC ON [PR_ActiveDifficulty] TO AruAdmin
--GRANT EXEC ON [PR_ActiveHikeType] TO AruAdmin
--GRANT EXEC ON [PR_ActiveAdmin] TO AruAdmin
--GRANT EXEC ON [PR_AddQuality] TO AruAdmin
--GRANT EXEC ON [PR_AddPrice] TO AruAdmin
--GRANT EXEC ON [PR_AddDifficulty] TO AruAdmin
--GRANT EXEC ON [PR_AddHikeType] TO AruAdmin
--GRANT EXEC ON [PR_EditQuality] TO AruAdmin
--GRANT EXEC ON [PR_EditPrice] TO AruAdmin
--GRANT EXEC ON [PR_EditDifficulty] TO AruAdmin
--GRANT EXEC ON [PR_EditHikeType] TO AruAdmin
--GRANT EXEC ON [PR_UpdateUser] TO AruAdmin
--GRANT EXEC ON [PR_ChangePassword] TO AruAdmin
--GRANT SELECT ON [View_Admin] TO AruAdmin
--GRANT SELECT ON [View_AdminICT] TO AruAdmin
--GRANT SELECT ON [View_Hiker] TO AruAdmin
--GRANT EXEC ON [PR_ActiveHiker] TO AruAdmin
--GRANT EXEC ON [PR_InactiveHiker] TO AruAdmin
--GRANT SELECT ON [EventLog] TO AruAdmin

GO