//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AruAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int IdEvent { get; set; }
        public string Description { get; set; }
        public string User { get; set; }
        public string ChangeType { get; set; }
        public string AffectedTable { get; set; }
        public System.DateTime Date { get; set; }
    }
}
