//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AruAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Hiker
    {
        public decimal IdCard { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Inactive { get; set; }
    }
}
